### PR TITLE
Add missing textures and models from Chorus' Version

### PR DESCRIPTION
**Pull request by lzlrd**
Textures may need to be optimised with OptiPNG. As of this commit,
textures were optimised with `optipng -o7 -nx` and then converted
from RGB to indexed colors.

### CODE REVIEW

**Comment by lzlrd** [comment]
Please do not merge this yet. These files were not optimised with OptiPNG (which I'm currently doing) and I accidentally included the `bettergrassandleaves` directory.

**Comment by lzlrd** [comment]
This is now ready for merging. It has been limited to only `minecraft` assets, optimised with OptiPNG, and has original Minecraft files removed (for LICENSE reasons).

**Comment by Athemis** [comment]
Thanks!

**Comment by Athemis** [comment]
Ok, I had to do some house cleaning after merging due to duplicate textures all over the place (not your fault as they are present in Chorus' archive as well). However, I'm not sure if I'd like to keep **all** of those alternative textures, especially the zombie varieties seem a bit overkill and don't follow a consistent style imho. But since that's just my personal taste, it's up to debate ;)

**Comment by Athemis** [comment]
Just realised while trying to fix some issues again, that Chorus' version is more or less a broken mess. It's working somehow, but it's obviously not based on the version of PixelPerfection that freejusticehere published (which is the one I used to start this repo). This leads to some issues namely that merging his changes re-introduces some issues I already fixed here.
Beside adding missing stuff (which is good), some things that were already working (occasionally even stuff that I fixed myself for this repo) broke again (e.g. wrong paths).

Hence, I'm reverting this for the moment (my last progress in cleaning up can be found in a dedicated branch 'broken-mess'). I'll try to merge everything manually now, beginning with missing textures only and leaving out anything fancy that is not strictly needed for Minecraft 1.16.

~~@lazerl0rd If you like to help, a good start would be to split this pull request up into smaller bits. E.g. a pull request that just adds missing textures and (if needed) models, but nothing else. Sound files, optifine etc. should all be seperate pulls as this will make it easier to identify and fix any issues occuring while merging those changes.~~

Give me a day to think this over again. Perhaps that's still fixable and I'm overreacting a bit right now ;)

**Comment by lzlrd** [comment]
> Ok, I had to do some house cleaning after merging due to duplicate textures all over the place (not your fault as they are present in Chorus' archive as well). However, I'm not sure if I'd like to keep **all** of those alternative textures, especially the zombie varieties seem a bit overkill and don't follow a consistent style imho. But since that's just my personal taste, it's up to debate ;)

I personally think any alternate textures that are similar to the "default" ones we have already are good to go.

> Just realised while trying to fix some issues again, that Chorus' version is more or less a broken mess. It's working somehow, but it's obviously not based on the version of PixelPerfection that freejusticehere published (which is the one I used to start this repo). This leads to some issues namely that merging his changes re-introduces some issues I already fixed here.
> Beside adding missing stuff (which is good), some things that were already working (occasionally even stuff that I fixed myself for this repo) broke again (e.g. wrong paths).

Yeah, sorry about that.
 
> Hence, I'm reverting this for the moment (my last progress in cleaning up can be found in a dedicated branch 'broken-mess'). I'll try to merge everything manually now, beginning with missing textures only and leaving out anything fancy that is not strictly needed for Minecraft 1.16.

That's probably the best choice for now.

> ~@lazerl0rd If you like to help, a good start would be to split this pull request up into smaller bits. E.g. a pull request that just adds missing textures and (if needed) models, but nothing else. Sound files, optifine etc. should all be seperate pulls as this will make it easier to identify and fix any issues occuring while merging those changes.~
> 
> Give me a day to think this over again. Perhaps that's still fixable and I'm overreacting a bit right now ;)

If you'd like, I can split the PR tomorrow. Just ping me here and I'll work on it.

**Comment by Athemis** [comment]
No need to be sorry (and to split the pull request) ;) I think I managed to clean it up already. See #4 
I checked for most of the issues I encountered when starting this repo and I'm pretty confident that none of those slipped in again :)
For the random mobs: I dropped quite a number of them (iron golem, most of the zombie textures) which I felt were too far away (style-wise) from the default ones. However, I'm open to comments and suggestions on that as this purely represents my own (probably very subjective) opinion.

**Pull request merged**
